### ISSUE TITLE
Iris installer displays a blank screen.

### ISSUE THREAD

**Issue by Alenygam** [IrisShaders/Iris-Installer#9]
I can't use the Iris installer because it displays a blank screen.

No error is thrown in the console. I am using Openjdk 16 on Arch Linux.

![image](https://user-images.githubusercontent.com/48835249/127173426-c97afde0-a0dc-45d3-a3eb-57be65be6f9d.png)

**Comment by ThatOneCalculator** [comment]
Yep. Same here.

**Comment by AlsoNiko** [comment]
https://bbs.archlinux.org/viewtopic.php?id=159016

**Comment by Alenygam** [comment]
Setting the _JAVA_AWT_WM_NONREPARENTING environment variable to 1 as seen in the forum post liked by @AlsoNiko solved the problem, I think this can be closed.
